# This is a basic workflow to help you get started with Actions

name: build release binaries

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
    inputs:
      tag: 
        description: 'Release tag'     
        required: true
        default: 'v0.0.0'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install scons
        run: brew install scons

      # Runs a set of commands using the runners shell
      - name: Compile headers
        run: |
          cd godot-cpp
          scons generate_bindings=yes target=release -j2
      
      - name: Compile binary
        run: scons platform=linux target=release
      
      - name: Commit linux binary
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'dardanbujupaj@users.noreply.github.com'
          git pull
          git add .
          git commit -am "Update linux binary for release ${{ github.event.inputs.tag }}"
          git push


  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install scons
        run: brew install scons

      # Runs a set of commands using the runners shell
      - name: Compile headers
        run: |
          cd godot-cpp
          scons generate_bindings=yes target=release -j2
      
      - name: Compile binary
        run: scons platform=macos target=release
      
      - name: Commit macos binary
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'dardanbujupaj@users.noreply.github.com'
          git pull
          git add .
          git commit -am "Update macos binary for release ${{ github.event.inputs.tag }}"
          git push
    

  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install scons
        run: pip install scons

      # Runs a set of commands using the runners shell
      - name: Compile headers
        shell: cmd
        run: |
          cd godot-cpp
          scons generate_bindings=yes target=release -j2
      
      - name: Compile binary
        shell: cmd
        run: |
          scons platform=windows target=release
      
      - name: Commit windows binary
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'dardanbujupaj@users.noreply.github.com'
          git pull
          git add .
          git commit -am "Update windows binary for release ${{ github.event.inputs.tag }}"
          git push
  
  
  tag-release:
    runs-on: ubuntu-latest

    needs: [build-linux, build-macos, build-windows]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Commit windows binary
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'dardanbujupaj@users.noreply.github.com'
          git tag ${{ github.event.inputs.tag }}
          git push --tags


        
        
        
        
        
